version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_install:
      - pip install -r docs/requirements.txt
      - pip install .

sphinx:
  builder: html
  configuration: docs/src/conf.py
  fail_on_warning: false

formats:
  - htmlzip
