from tekore.client.api.album import SpotifyAlbum
from tekore.client.api.artist import SpotifyArtist
from tekore.client.api.browse import SpotifyBrowse
from tekore.client.api.episode import SpotifyEpisode
from tekore.client.api.follow import SpotifyFollow
from tekore.client.api.library import SpotifyLibrary
from tekore.client.api.personalisation import SpotifyPersonalisation
from tekore.client.api.player import SpotifyPlayer
from tekore.client.api.playlist import SpotifyPlaylist
from tekore.client.api.search import SpotifySearch
from tekore.client.api.show import SpotifyShow
from tekore.client.api.track import SpotifyTrack
from tekore.client.api.user import SpotifyUser
